

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build: ./backend
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app-net
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-net
    ports:
      - "80:80"

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
